CREATE IF NOT EXISTS TABLE elements (
    id SERIAL PRIMARY KEY,
    set_id INTEGER NOT NULL,
    english VARCHAR(64) NOT NULL,
    polish VARCHAR(64) NOT NULL,
    synonym VARCHAR(64), NOT NULL,
    exampleSentence TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);